baseURL = "https://www.mericanrx.com"
languageCode = "en-us"
title = "Merican RX"
theme = "ananke"
publishDir = "public"
[permalinks]
  posts = "/:filename"


enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
